spring.application.name=backhelp

# Conex�o com o Banco MySQL
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/helpdesk_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configura��es do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
